### ISSUE TITLE
Problems with amount in URI or QR Code

### ISSUE THREAD

**Issue by ffsolutions** [perawallet/pera-wallet#128]
Dear all.

The amount is being recognized incorrectly. I am using microAlgos according to the URI scheme (https://developer.algorand.org/docs/get-details/transactions/payment_prompts/), e.g., ?amount=150500000. The expected result would be 150.5 Algos, but it is recognizing 150,5,5.
The same happens with other variations, such as ?amount=10510000, which is recognized as 10,51,51.

Tested on MacOS 15.3.1  and iOS 18.3.1. Pera Algo Wallet Version 5.17.1.

I am working on a large project, and we came across this issue. The curious thing is that it was working fine before without any problems.

Thank you for the great work you are doing; this Wallet is amazing.

Regards

algorand://TMTAD6N22HCS2LKH7677L2KFLT3PAQWY6M4JFQFXQS32ECBFC23F57RYX4?amount=150500000

![Image](https://github.com/user-attachments/assets/bd0a8abe-4550-4968-a55e-1ef613753d78)

**Comment by filipetamota** [comment]
Hello!
Thanks for reporting it, we will look into it. 
Could you just share with us a video recording and the Locale of the device being tested?
Regards

**Comment by ffsolutions** [comment]
Thank you, you can test it with the examples from the documentation I sent. Here is a video testing a URI example.

https://github.com/user-attachments/assets/6a68b661-e407-4ac8-9f42-a771d0b2c2fc

Regards

**Comment by filipetamota** [comment]
Hello!
Thanks for all the info.
The issue is fixed and the fix will be released on the 5.19.0 version.
Regards

**Comment by ffsolutions** [comment]
Hi Filipe, how are you? 

Thanks for the new version!
 I ran all the tests here and it's partially resolved. It now correctly recognizes the value, but when proceeding, the error **"An error occurred."** appears and it doesn't let you continue. However, if you delete the number and type it again, it goes through and works. Could you please check this? Here's the video example and the URI I used, but the issue happens with all of them.

algorand://TMTAD6N22HCS2LKH7677L2KFLT3PAQWY6M4JFQFXQS32ECBFC23F57RYX4?amount=55500000

https://github.com/user-attachments/assets/2d45fa5e-edf2-4fbd-b202-c5f8f50c8b6a

Regards,

Felipe Vieira

**Comment by filipetamota** [comment]
Hey Felipe,

Thanks again for reporting it.
We've identified the issue and solved it. It will be released on the 5.21.0 version.

Regards

**Comment by ffsolutions** [comment]
Hi @filipetamota !

It worked perfectly! It's already in production in our project if you'd like to see how it turned out. Thank you very much.

https://www.youtube.com/watch?v=iOcRf580gVw     at 8:00

https://startups.investments/invite/fsv

Regards,

Felipe Vieira

**Comment by filipetamota** [comment]
Hey Felipe,

Happy to know! And thanks for the shout-out on your Youtube channel!

Best regards

P.S.: If everything is working correctly now, could you close this issue? Thanks!
